# Site Settings
title: "Emil Gasimov"
description: "MSc AI Graduate Researcher & Demonstrator at QMUL"
url: "https://ellysian.github.io"
baseurl: "" 
repository: "ellysian/ellysian.github.io" # Helpful for some plugins

# Theme Settings
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "contrast"
search: true

# Localization/Dates
timezone: "Europe/London"
locale: "en-GB"

# Front Matter Defaults (This applies settings to all pages automatically)
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true
      classes: wide # Makes the content area slightly wider for better readability

# Sidebar/Author Info
author:
  # name   : "Emil Gasimov"
  # avatar : "/assets/images/bio-photo.jpg"
  bio    : "Junior Research Associate in Cardiac AI at QMUL."
  location: "London, UK"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ellysian"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:e.gasimov@se24.qmul.ac.uk"

# Build Settings
markdown: kramdown
highlighter: rouge
include: ["_pages"]
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# Pagination
paginate: 5
paginate_path: /page:num/